export const PermissionConstants = {
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_READ_ALL: 'USER_READ_ALL',
  USER_READ_BY_UID: 'USER_READ_BY_UID',
  USER_WRITE: 'USER_WRITE',
  USER_DELETE: 'USER_DELETE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_ADMIN_WRITE: 'USER_ADMIN_WRITE',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_READ: 'PRODUCT_READ',
  PRODUCT_READ_ALL: 'PRODUCT_READ_ALL',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  CATEGORY_READ: 'CATEGORY_READ',
  CATEGORY_READ_ALL: 'CATEGORY_READ_ALL',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  STORE_WRITE: 'STORE_WRITE',
  STORE_DELETE: 'STORE_DELETE',
  ORDER_READ_ALL: 'ORDER_READ_ALL',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL_ALL: 'ORDER_CANCEL_ALL',
  ORDER_PAYMENT_COLLECT: 'ORDER_PAYMENT_COLLECT',
  ECOM_CUSTOMER_READ: 'ECOM_CUSTOMER_READ',
  ECOM_RIDER_READ: 'ECOM_RIDER_READ',
  ECOM_STORE_MANAGER_READ: 'ECOM_STORE_MANAGER_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_ASSIGN_USER: 'ROLE_ASSIGN_USER',
  AGENCY_ROLES_READ: 'AGENCY_ROLES_READ',
  PERMISSION_READ: 'PERMISSION_READ',
  GEO_REGION_CREATE: 'GEO_REGION_CREATE',
  GEO_REGION_READ: 'GEO_REGION_READ',
  GEO_REGION_UPDATE: 'GEO_REGION_UPDATE',
  GEO_REGION_DELETE: 'GEO_REGION_DELETE',
  GEO_LANDMARK_CREATE: 'GEO_LANDMARK_CREATE',
  GEO_LANDMARK_READ: 'GEO_LANDMARK_READ',
  GEO_LANDMARK_UPDATE: 'GEO_LANDMARK_UPDATE',
  GEO_LANDMARK_DELETE: 'GEO_LANDMARK_DELETE',
  ADDRESS_CREATE: 'ADDRESS_CREATE',
  ADDRESS_READ: 'ADDRESS_READ',
  ADDRESS_READ_ALL: 'ADDRESS_READ_ALL',
  ADDRESS_WRITE: 'ADDRESS_WRITE',
  ADDRESS_DELETE: 'ADDRESS_DELETE',
  TAG_CREATE: 'TAG_CREATE',
  TAG_READ: 'TAG_READ',
  TAG_UPDATE: 'TAG_UPDATE',
  TAG_DELETE: 'TAG_DELETE',
  CUSTOMER_GROUP_CREATE: 'CUSTOMER_GROUP_CREATE',
  CUSTOMER_GROUP_READ: 'CUSTOMER_GROUP_READ',
  CUSTOMER_GROUP_UPDATE: 'CUSTOMER_GROUP_UPDATE',
  CUSTOMER_GROUP_MEMBER_ADD: 'CUSTOMER_GROUP_MEMBER_ADD',
  CUSTOMER_GROUP_MEMBER_REMOVE: 'CUSTOMER_GROUP_MEMBER_REMOVE',
  VOUCHER_CREATE: 'VOUCHER_CREATE',
  VOUCHER_READ_ALL: 'VOUCHER_READ_ALL',
  VOUCHER_UPDATE: 'VOUCHER_UPDATE',
  VOUCHER_DELETE: 'VOUCHER_DELETE',
  ORDER_PAYMENT_READ_ALL: 'ORDER_PAYMENT_READ_ALL',
  PARTIAL_PAYMENT_POLICY_CREATE: 'PARTIAL_PAYMENT_POLICY_CREATE',
  PARTIAL_PAYMENT_POLICY_READ: 'PARTIAL_PAYMENT_POLICY_READ',
  PARTIAL_PAYMENT_POLICY_UPDATE: 'PARTIAL_PAYMENT_POLICY_UPDATE',
  DELIVERY_ADDRESS_READ_ALL: 'DELIVERY_ADDRESS_READ_ALL',
  DELIVERY_ADDRESS_WRITE_ALL: 'DELIVERY_ADDRESS_WRITE_ALL',
  DELIVERY_ADDRESS_DELETE_ALL: 'DELIVERY_ADDRESS_DELETE_ALL',
  DELIVERY_ADDRESS_VERIFY: 'DELIVERY_ADDRESS_VERIFY',
  AGENCY_CREATE: 'AGENCY_CREATE',
  AGENCY_READ: 'AGENCY_READ',
  AGENCY_READ_ALL: 'AGENCY_READ_ALL',
  AGENCY_UPDATE: 'AGENCY_UPDATE',
  AGENCY_DELETE: 'AGENCY_DELETE',
  AGENCY_BUILDING_MANAGE: 'AGENCY_BUILDING_MANAGE',
  AGENCY_ADMIN_READ: 'AGENCY_ADMIN_READ',
  AGENCY_ADMIN_ADD: 'AGENCY_ADMIN_ADD',
  AGENCY_ADMIN_REMOVE: 'AGENCY_ADMIN_REMOVE',
  BUILDING_CREATE: 'BUILDING_CREATE',
  BUILDING_READ: 'BUILDING_READ',
  BUILDING_READ_ALL: 'BUILDING_READ_ALL',
  BUILDING_UPDATE: 'BUILDING_UPDATE',
  BUILDING_DELETE: 'BUILDING_DELETE',
  BUILDING_FLOOR_MANAGE: 'BUILDING_FLOOR_MANAGE',
  TENANT_READ_ALL: 'TENANT_READ_ALL',
  TENANT_WRITE_ALL: 'TENANT_WRITE_ALL',
  TENANT_DELETE_ALL: 'TENANT_DELETE_ALL',
  TENANT_DOCUMENT_READ_ALL: 'TENANT_DOCUMENT_READ_ALL',
  TENANT_DOCUMENT_DELETE_ALL: 'TENANT_DOCUMENT_DELETE_ALL',
  LEASE_AGREEMENT_READ_ALL: 'LEASE_AGREEMENT_READ_ALL',
  LEASE_AGREEMENT_WRITE: 'LEASE_AGREEMENT_WRITE',
  LEASE_AGREEMENT_DELETE: 'LEASE_AGREEMENT_DELETE',
  LEASE_AMENDMENT_CREATE: 'LEASE_AMENDMENT_CREATE',
  LEASE_AMENDMENT_READ: 'LEASE_AMENDMENT_READ',
  LEASE_AMENDMENT_READ_ALL: 'LEASE_AMENDMENT_READ_ALL',
  LEASE_AMENDMENT_WRITE: 'LEASE_AMENDMENT_WRITE',
  LEASE_AMENDMENT_DELETE: 'LEASE_AMENDMENT_DELETE',
  ROOM_APPLICATION_READ_ALL: 'ROOM_APPLICATION_READ_ALL',
  ROOM_APPLICATION_REVIEW_ALL: 'ROOM_APPLICATION_REVIEW_ALL',
  TENANT_MESSAGE_CREATE: 'TENANT_MESSAGE_CREATE',
  TENANT_MESSAGE_READ: 'TENANT_MESSAGE_READ',
  TENANT_MESSAGE_READ_ALL: 'TENANT_MESSAGE_READ_ALL',
  TENANT_MESSAGE_WRITE: 'TENANT_MESSAGE_WRITE',
  TENANT_MESSAGE_DELETE: 'TENANT_MESSAGE_DELETE',
  VERIFICATION_SNAPSHOT_CREATE: 'VERIFICATION_SNAPSHOT_CREATE',
  VERIFICATION_SNAPSHOT_READ_ALL: 'VERIFICATION_SNAPSHOT_READ_ALL',
  VERIFICATION_SNAPSHOT_WRITE_ALL: 'VERIFICATION_SNAPSHOT_WRITE_ALL',
  VERIFICATION_SNAPSHOT_DELETE_ALL: 'VERIFICATION_SNAPSHOT_DELETE_ALL',
  RENT_PAYMENT_READ_ALL: 'RENT_PAYMENT_READ_ALL',
  RENT_PAYMENT_WRITE_ALL: 'RENT_PAYMENT_WRITE_ALL',
  RENT_PAYMENT_DELETE: 'RENT_PAYMENT_DELETE',
  RENT_ARREAR_READ: 'RENT_ARREAR_READ',
  CHAT_ADMIN_READ: 'CHAT_ADMIN_READ',
  CHAT_ADMIN_WRITE: 'CHAT_ADMIN_WRITE',
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',
  APP_MANAGEMENT_READ: 'APP_MANAGEMENT_READ',
  APP_MANAGEMENT_WRITE: 'APP_MANAGEMENT_WRITE',
  NOTIFICATION_POLICY_READ: 'NOTIFICATION_POLICY_READ',
  NOTIFICATION_POLICY_WRITE: 'NOTIFICATION_POLICY_WRITE',

  /*
   * Agency-scoped forms.
   *
   * The registry pairs most operations: an `_ALL` permission that reaches every
   * record on the platform, and a plain one that reaches only what the caller's
   * agency or building grant covers. Only the `_ALL` half was declared here, so
   * every gate asked the platform-wide question — and an AGENCY_ADMIN, who
   * holds the scoped half, was shown nothing. See `PermissionSets` below.
   */
  AGENCY_CREATE_FOR_OTHERS: 'AGENCY_CREATE_FOR_OTHERS',
  /** Dashboard figures, one permission per scope. */
  STATS_PLATFORM_READ: 'STATS_PLATFORM_READ',
  STATS_AGENCY_READ: 'STATS_AGENCY_READ',
  STATS_BUILDING_READ: 'STATS_BUILDING_READ',
  STATS_ECOM_READ: 'STATS_ECOM_READ',
  STATS_TENANT_READ: 'STATS_TENANT_READ',
  /** Edits the contract document for one agency, its buildings and its rooms. */
  CONTRACT_TEMPLATE_MANAGE: 'CONTRACT_TEMPLATE_MANAGE',
  /** Super-admin only: the platform master every agency forks from. */
  CONTRACT_TEMPLATE_MANAGE_ALL: 'CONTRACT_TEMPLATE_MANAGE_ALL',
  BUILDING_MANAGE: 'BUILDING_MANAGE',
  BUILDING_TENANT_MANAGE: 'BUILDING_TENANT_MANAGE',
  FLOOR_CREATE: 'FLOOR_CREATE',
  FLOOR_READ: 'FLOOR_READ',
  FLOOR_UPDATE: 'FLOOR_UPDATE',
  FLOOR_DELETE: 'FLOOR_DELETE',
  LANDLORD_CREATE: 'LANDLORD_CREATE',
  LANDLORD_READ: 'LANDLORD_READ',
  LEASE_CREATE: 'LEASE_CREATE',
  LEASE_READ: 'LEASE_READ',
  LEASE_AGREEMENT_READ: 'LEASE_AGREEMENT_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  RENT_ARREAR_WRITE: 'RENT_ARREAR_WRITE',
  RENT_PAYMENT_CREATE: 'RENT_PAYMENT_CREATE',
  RENT_PAYMENT_READ: 'RENT_PAYMENT_READ',
  RENT_PAYMENT_WRITE: 'RENT_PAYMENT_WRITE',
  ROOM_APPLICATION_CREATE: 'ROOM_APPLICATION_CREATE',
  ROOM_APPLICATION_READ: 'ROOM_APPLICATION_READ',
  ROOM_APPLICATION_REVIEW: 'ROOM_APPLICATION_REVIEW',
  ROOM_CREATE: 'ROOM_CREATE',
  ROOM_READ: 'ROOM_READ',
  ROOM_UPDATE: 'ROOM_UPDATE',
  ROOM_DELETE: 'ROOM_DELETE',
  SINGLE_TENANT_READ: 'SINGLE_TENANT_READ',
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_READ: 'TENANT_READ',
  TENANT_WRITE: 'TENANT_WRITE',
  TENANT_DELETE: 'TENANT_DELETE',
  TENANT_DOCUMENT_CREATE: 'TENANT_DOCUMENT_CREATE',
  TENANT_DOCUMENT_READ: 'TENANT_DOCUMENT_READ',
  TENANT_DOCUMENT_UPDATE: 'TENANT_DOCUMENT_UPDATE',
  TENANT_DOCUMENT_DELETE: 'TENANT_DOCUMENT_DELETE',
  TENANT_DOCUMENT_UPDATE_ALL: 'TENANT_DOCUMENT_UPDATE_ALL',
  USER_FORCE_LOGOUT: 'USER_FORCE_LOGOUT',
  // Re-opening a sealed snapshot. Granted to no role by construction, so it
  // reaches only SUPER_ADMIN — sealing exists so the agency holding the
  // documents cannot decide to look at them again.
  SNAPSHOT_UNSEAL: 'SNAPSHOT_UNSEAL',
  AUDIT_READ: 'AUDIT_READ',
  VERIFICATION_SNAPSHOT_READ: 'VERIFICATION_SNAPSHOT_READ',
  VERIFICATION_SNAPSHOT_WRITE: 'VERIFICATION_SNAPSHOT_WRITE',
  VERIFICATION_SNAPSHOT_DELETE: 'VERIFICATION_SNAPSHOT_DELETE'
} as const;

export type Permission = typeof PermissionConstants[keyof typeof PermissionConstants];

const P = PermissionConstants;

/**
 * "Can this operator do X" — answered without caring which scope grants it.
 *
 * A gate must accept **either** half of a scoped pair: a super admin holds
 * `TENANT_READ_ALL`, an agency admin holds `TENANT_READ`, and both are entitled
 * to the tenants screen. Gating on the `_ALL` half alone hid most of the app
 * from every agency role.
 *
 * `app-permission-gate` and `ActiveContextService.canAny` already OR a list, so
 * these are drop-in: `[permissions]="PermissionSets.TENANT_VIEW"`.
 *
 * Never hardcode which role holds what — these are unions of permission names,
 * and the backend decides who has them.
 */
export const PermissionSets = {
  TENANT_VIEW: [P.TENANT_READ_ALL, P.TENANT_READ, P.SINGLE_TENANT_READ],
  TENANT_CREATE: [P.TENANT_CREATE, P.BUILDING_TENANT_MANAGE],
  TENANT_WRITE: [P.TENANT_WRITE_ALL, P.TENANT_WRITE],
  TENANT_DELETE: [P.TENANT_DELETE_ALL, P.TENANT_DELETE],

  TENANT_DOCUMENT_VIEW: [P.TENANT_DOCUMENT_READ_ALL, P.TENANT_DOCUMENT_READ],
  TENANT_DOCUMENT_WRITE: [P.TENANT_DOCUMENT_UPDATE_ALL, P.TENANT_DOCUMENT_UPDATE, P.TENANT_DOCUMENT_CREATE],
  TENANT_DOCUMENT_DELETE: [P.TENANT_DOCUMENT_DELETE_ALL, P.TENANT_DOCUMENT_DELETE],

  TENANT_MESSAGE_VIEW: [P.TENANT_MESSAGE_READ_ALL, P.TENANT_MESSAGE_READ],

  LEASE_VIEW: [P.LEASE_AGREEMENT_READ_ALL, P.LEASE_AGREEMENT_READ, P.LEASE_READ],
  LEASE_WRITE: [P.LEASE_AGREEMENT_WRITE, P.LEASE_CREATE],
  LEASE_AMENDMENT_VIEW: [P.LEASE_AMENDMENT_READ_ALL, P.LEASE_AMENDMENT_READ],

  RENT_PAYMENT_VIEW: [P.RENT_PAYMENT_READ_ALL, P.RENT_PAYMENT_READ],
  RENT_PAYMENT_WRITE: [P.RENT_PAYMENT_WRITE_ALL, P.RENT_PAYMENT_WRITE, P.RENT_PAYMENT_CREATE],

  ROOM_APPLICATION_VIEW: [P.ROOM_APPLICATION_READ_ALL, P.ROOM_APPLICATION_READ],
  ROOM_APPLICATION_REVIEW: [P.ROOM_APPLICATION_REVIEW_ALL, P.ROOM_APPLICATION_REVIEW],

  SNAPSHOT_VIEW: [P.VERIFICATION_SNAPSHOT_READ_ALL, P.VERIFICATION_SNAPSHOT_READ],
  SNAPSHOT_WRITE: [P.VERIFICATION_SNAPSHOT_WRITE_ALL, P.VERIFICATION_SNAPSHOT_WRITE],
  SNAPSHOT_DELETE: [P.VERIFICATION_SNAPSHOT_DELETE_ALL, P.VERIFICATION_SNAPSHOT_DELETE],

  BUILDING_VIEW: [P.BUILDING_READ_ALL, P.BUILDING_READ],
  AGENCY_VIEW: [P.AGENCY_READ_ALL, P.AGENCY_READ],
  ROOM_VIEW: [P.ROOM_READ, P.BUILDING_READ_ALL, P.BUILDING_READ]
} as const;
