export const ApiUrls = {
  login: 'v1/auth/login',
  checkLoginMethod: 'v1/auth/check-login-method',
  loginOtpRequest: 'v1/auth/login-otp/request',
  loginOtpConfirm: 'v1/auth/login-otp/confirm',
  signupVerifyPhoneRequest: 'v1/auth/signup/verify-phone/request',
  signupVerifyPhoneConfirm: 'v1/auth/signup/verify-phone/confirm',
  signup: 'v1/auth/signup',
  refreshToken: 'v1/auth/refresh-token',
  logout: 'v1/auth/logout',
  passwordResetInitiate: 'v1/auth/password-reset/initiate',
  passwordResetAdminInitiate: 'v1/auth/password-reset/admin-initiate',
  passwordResetConfirm: 'v1/auth/password-reset/confirm',
  passwordChange: 'v1/auth/password-change',
  passwordSet: 'v1/auth/password-set',
  userProfile: 'v1/users/profile',
  users: 'v1/users',
  userById: (id: number | string) => `v1/users/${id}`,
  userByUid: (uid: string) => `v1/users/by-uid/${uid}`,
  userResetPassword: (id: number | string) => `v1/users/${id}/reset-password`,
  userAdminUpdate: (id: number | string) => `v1/users/${id}/admin-update`,
  ecomUsers: {
    customers: 'v1/ecom/users/customers',
    riders: 'v1/ecom/users/riders',
    storeManagers: 'v1/ecom/users/store-managers'
  },
  products: 'v1/products',
  productById: (id: number | string) => `v1/products/${id}`,
  productBySku: (sku: string) => `v1/products/sku/${sku}`,
  productBySlug: (slug: string) => `v1/products/slug/${slug}`,
  productByCategory: (categoryId: number | string) => `v1/products/category/${categoryId}`,
  productBySubCategory: (subCategoryId: number | string) => `v1/products/subcategory/${subCategoryId}`,
  categories: 'v1/categories',
  categoryHierarchy: 'v1/categories/hierarchy',
  categorySearch: 'v1/categories/search',
  categoryById: (id: number | string) => `v1/categories/${id}`,
  categoryBySlug: (slug: string) => `v1/categories/slug/${slug}`,
  categoryProductCount: (id: number | string) => `v1/categories/${id}/product-count`,
  categorySubcategories: 'v1/categories/subcategories',
  stores: 'v1/stores',
  storeById: (id: number | string) => `v1/stores/${id}`,
  orders: 'v1/orders',
  orderById: (id: number | string) => `v1/orders/${id}`,
  orderByCustomer: (customerId: number | string) => `v1/orders/customer/${customerId}`,
  orderMyOrders: 'v1/orders/my-orders',
  orderValidateCart: 'v1/orders/validate-cart',
  orderCancel: (id: number | string) => `v1/orders/${id}/cancel`,
  orderMarkCashCollected: (id: number | string) => `v1/orders/${id}/mark-cash-collected`,
  orderMarkMpesaCollected: (id: number | string) => `v1/orders/${id}/mark-mpesa-collected`
} as const;
