export const ApiUrls = {
  login: 'v1/auth/login',
  checkLoginMethod: 'v1/auth/check-login-method',
  loginOtpRequest: 'v1/auth/login-otp/request',
  loginOtpConfirm: 'v1/auth/login-otp/confirm',
  signupVerifyPhoneRequest: 'v1/auth/signup/verify-phone/request',
  signupVerifyPhoneConfirm: 'v1/auth/signup/verify-phone/confirm',
  signup: 'v1/auth/signup',
  refreshToken: 'v1/auth/refresh-token',
  logout: 'v1/auth/logout',
  passwordResetInitiate: 'v1/auth/password-reset/initiate',
  passwordResetAdminInitiate: 'v1/auth/password-reset/admin-initiate',
  passwordResetConfirm: 'v1/auth/password-reset/confirm',
  passwordChange: 'v1/auth/password-change',
  passwordSet: 'v1/auth/password-set',
  userProfile: 'v1/users/profile',
  users: 'v1/users',
  userById: (id: number | string) => `v1/users/${id}`,
  userByUid: (uid: string) => `v1/users/by-uid/${uid}`,
  myTenancyProfile: 'v1/users/me/tenancy-profile',
  userResetPassword: (id: number | string) => `v1/users/${id}/reset-password`,
  userAdminUpdate: (id: number | string) => `v1/users/${id}/admin-update`,
  ecomUsers: {
    customers: 'v1/ecom/users/customers',
    riders: 'v1/ecom/users/riders',
    storeManagers: 'v1/ecom/users/store-managers'
  },
  products: 'v1/products',
  productById: (id: number | string) => `v1/products/${id}`,
  productBySku: (sku: string) => `v1/products/sku/${sku}`,
  productBySlug: (slug: string) => `v1/products/slug/${slug}`,
  productByCategory: (categoryId: number | string) => `v1/products/category/${categoryId}`,
  productBySubCategory: (subCategoryId: number | string) => `v1/products/subcategory/${subCategoryId}`,
  categories: 'v1/categories',
  categoryHierarchy: 'v1/categories/hierarchy',
  categorySearch: 'v1/categories/search',
  categoryById: (id: number | string) => `v1/categories/${id}`,
  categoryBySlug: (slug: string) => `v1/categories/slug/${slug}`,
  categoryProductCount: (id: number | string) => `v1/categories/${id}/product-count`,
  categorySubcategories: 'v1/categories/subcategories',
  addresses: 'v1/addresses',
  addressById: (id: number | string) => `v1/addresses/${id}`,
  addressCounties: 'v1/addresses/counties',
  addressCountyById: (id: number | string) => `v1/addresses/counties/${id}`,
  addressCities: 'v1/addresses/cities',
  addressCityById: (id: number | string) => `v1/addresses/cities/${id}`,
  addressCitiesByCounty: (countyId: number | string) => `v1/addresses/counties/${countyId}/cities`,
  addressSubCounties: 'v1/addresses/sub-counties',
  addressSubCountyById: (id: number | string) => `v1/addresses/sub-counties/${id}`,
  addressSubCountiesByCounty: (countyId: number | string) => `v1/addresses/counties/${countyId}/sub-counties`,
  addressWards: 'v1/addresses/wards',
  addressWardById: (id: number | string) => `v1/addresses/wards/${id}`,
  addressWardsBySubCounty: (subCountyId: number | string) => `v1/addresses/sub-counties/${subCountyId}/wards`,
  addressWardsByCounty: (countyId: number | string) => `v1/addresses/counties/${countyId}/wards`,
  /** POST only — there is no unscoped town listing. */
  addressTownCreate: 'v1/addresses/towns',
  addressTownById: (id: number | string) => `v1/addresses/towns/${id}`,
  addressTownsByCity: (cityId: number | string) => `v1/addresses/cities/${cityId}/towns`,
  addressTownsByCounty: (countyId: number | string) => `v1/addresses/counties/${countyId}/towns`,
  stores: 'v1/stores',
  storeById: (id: number | string) => `v1/stores/${id}`,
  orders: 'v1/orders',
  orderById: (id: number | string) => `v1/orders/${id}`,
  orderByCustomer: (customerId: number | string) => `v1/orders/customer/${customerId}`,
  orderMyOrders: 'v1/orders/my-orders',
  orderValidateCart: 'v1/orders/validate-cart',
  orderCancel: (id: number | string) => `v1/orders/${id}/cancel`,
  orderMarkCashCollected: (id: number | string) => `v1/orders/${id}/mark-cash-collected`,
  orderMarkMpesaCollected: (id: number | string) => `v1/orders/${id}/mark-mpesa-collected`,
  productActive: 'v1/products/active',
  productCheckSku: 'v1/products/check-sku',
  productCheckSlug: 'v1/products/check-slug',
  productFeaturedByCategory: (categoryId: number | string) => `v1/products/category/${categoryId}/featured`,
  productFeaturedBySubCategory: (subCategoryId: number | string) => `v1/products/subcategory/${subCategoryId}/featured`,
  productImages: (productId: number | string) => `v1/products/${productId}/images`,
  productImagesBulk: (productId: number | string) => `v1/products/${productId}/images/bulk`,
  productImageById: (productId: number | string, imageId: number | string) => `v1/products/${productId}/images/${imageId}`,
  productImagePrimary: (productId: number | string, imageId: number | string) => `v1/products/${productId}/images/${imageId}/primary`,
  productVariants: (productId: number | string) => `v1/products/${productId}/variants`,
  productVariantById: (productId: number | string, variantId: number | string) => `v1/products/${productId}/variants/${variantId}`,
  productVariantImages: (productId: number | string, variantId: number | string) => `v1/products/${productId}/variants/${variantId}/images`,
  productVariantImageById: (productId: number | string, variantId: number | string, imageId: number | string) => `v1/products/${productId}/variants/${variantId}/images/${imageId}`,
  productVariantImagePrimary: (productId: number | string, variantId: number | string, imageId: number | string) => `v1/products/${productId}/variants/${variantId}/images/${imageId}/primary`,
  productDiscounts: (productId: number | string) => `v1/products/${productId}/discounts`,
  productDiscountsActive: (productId: number | string) => `v1/products/${productId}/discounts/active`,
  productDiscountById: (productId: number | string, discountId: number | string) => `v1/products/${productId}/discounts/${discountId}`,
  productDiscountToggle: (productId: number | string, discountId: number | string) => `v1/products/${productId}/discounts/${discountId}/toggle`,
  tags: 'v1/tags',
  tagById: (id: number | string) => `v1/tags/${id}`,
  tagBySlug: (slug: string) => `v1/tags/slug/${slug}`,
  tagSearch: 'v1/tags/search',
  productTags: (productId: number | string) => `v1/products/${productId}/tags`,
  productTagById: (productId: number | string, tagId: number | string) => `v1/products/${productId}/tags/${tagId}`,
  customerGroups: 'v1/customer-groups',
  customerGroupById: (id: number | string) => `v1/customer-groups/${id}`,
  customerGroupMembers: (id: number | string) => `v1/customer-groups/${id}/members`,
  customerGroupMemberById: (id: number | string, userId: number | string) => `v1/customer-groups/${id}/members/${userId}`,
  vouchers: 'v1/vouchers',
  voucherById: (id: number | string) => `v1/vouchers/${id}`,
  voucherStats: (id: number | string) => `v1/vouchers/${id}/stats`,
  voucherMine: 'v1/vouchers/my-vouchers',
  voucherValidate: 'v1/vouchers/validate',
  voucherValidateForCart: 'v1/vouchers/validate-for-cart',
  payments: 'v1/payments',
  paymentById: (id: number | string) => `v1/payments/${id}`,
  paymentStatusByOrder: (orderId: number | string) => `v1/payments/order/${orderId}/status`,
  paymentOrderSearch: 'v1/payments/order-payment-search',
  partialPaymentPolicies: 'v1/partial-payments/policies',
  partialPaymentPolicyById: (id: number | string) => `v1/partial-payments/policies/${id}`,
  partialPaymentEligibility: 'v1/partial-payments/check-eligibility',
  partialPaymentRecord: (orderId: number | string) => `v1/partial-payments/orders/${orderId}/record`,
  deliveryAddresses: 'v1/delivery-addresses',
  deliveryAddressesPaginated: 'v1/delivery-addresses/paginated',
  deliveryAddressesByUser: (userId: number | string) => `v1/delivery-addresses/user/${userId}`,
  deliveryAddressById: (id: number | string) => `v1/delivery-addresses/${id}`,
  deliveryAddressVerify: (id: number | string) => `v1/delivery-addresses/${id}/verify`,
  agencies: 'v1/agencies',
  agencyById: (id: number | string) => `v1/agencies/${id}`,
  notificationChannelReference: 'v1/notification-channels/reference',
  notificationChannelPolicies: 'v1/notification-channels/policies',
  notificationChannelPolicy: (topic: string) => `v1/notification-channels/policies/${topic}`,
  notificationChannelPreferences: 'v1/notification-channels/preferences',
  notificationChannelPreference: (topic: string) => `v1/notification-channels/preferences/${topic}`,
  agencyBuildings: (agencyId: number | string) => `v1/agencies/${agencyId}/buildings`,
  agencyAddresses: (agencyId: number | string) => `v1/agencies/${agencyId}/addresses`,
  agencyAddressById: (agencyId: number | string, addressId: number | string) => `v1/agencies/${agencyId}/addresses/${addressId}`,
  userAgencies: 'v1/agencies/user-agencies',
  agencyAdmins: (agencyId: number | string) => `v1/agencies/${agencyId}/admins`,
  agencyAdminById: (agencyId: number | string, userId: number | string) => `v1/agencies/${agencyId}/admins/${userId}`,
  buildings: 'v1/buildings',
  buildingById: (agencyId: number | string, buildingId: number | string) => `v1/buildings/${agencyId}/${buildingId}`,
  buildingsByAgency: (agencyId: number | string) => `v1/buildings/agency/${agencyId}`,
  userBuildings: 'v1/buildings/user-buildings',
  buildingAddress: (agencyId: number | string, buildingId: number | string) => `v1/buildings/${agencyId}/${buildingId}/address`,
  buildingFloors: (agencyId: number | string, buildingId: number | string) => `v1/buildings/${agencyId}/${buildingId}/floors`,
  buildingFloorById: (agencyId: number | string, buildingId: number | string, floorId: number | string) => `v1/buildings/${agencyId}/${buildingId}/floors/${floorId}`,
  buildingFloorRooms: (agencyId: number | string, buildingId: number | string, floorId: number | string) => `v1/buildings/${agencyId}/${buildingId}/floors/${floorId}/rooms`,
  buildingRoomById: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/buildings/${agencyId}/${buildingId}/rooms/${roomId}`,
  buildingRoomEffectiveTerms: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/buildings/${agencyId}/${buildingId}/rooms/${roomId}/effective-terms`,
  buildingAvailableRooms: 'v1/buildings/available-rooms',
  roomUtilities: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/${roomId}`,
  roomUtilitiesActive: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/${roomId}/active`,
  buildingUtilityById: (agencyId: number | string, buildingId: number | string, utilityId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/utility/${utilityId}`,
  buildingUtilities: (agencyId: number | string, buildingId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/utilities`,
  buildingUtilityApplyToAll: (agencyId: number | string, buildingId: number | string, utilityId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/utility/${utilityId}/apply-to-all`,
  buildingUtilityRemoveFromAll: (agencyId: number | string, buildingId: number | string, utilityId: number | string) => `v1/building-utilities/${agencyId}/${buildingId}/utility/${utilityId}/from-all`,
  tenants: 'v1/tenants',
  tenantSelfRegister: 'v1/tenants/self-register',
  tenantProfile: 'v1/tenants/tenant-profile',
  tenantById: (agencyId: number | string, buildingId: number | string, id: number | string) => `v1/tenants/${agencyId}/${buildingId}/${id}`,
  tenantFullById: (agencyId: number | string, buildingId: number | string, id: number | string) => `v1/tenants/${agencyId}/${buildingId}/${id}/full`,
  tenantLandlordUpdate: (agencyId: number | string, buildingId: number | string, id: number | string) => `v1/tenants/${agencyId}/${buildingId}/${id}/landlord`,
  tenantsByBuilding: (agencyId: number | string, buildingId: number | string) => `v1/tenants/${agencyId}/${buildingId}`,
  tenantsActiveByBuilding: (agencyId: number | string, buildingId: number | string) => `v1/tenants/active/${agencyId}/${buildingId}`,
  tenantsByRoom: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/tenants/${agencyId}/${buildingId}/room/${roomId}`,
  tenantsByAgency: (agencyId: number | string) => `v1/tenants/agency/${agencyId}`,
  tenantsByUser: (userId: number | string) => `v1/tenants/user/${userId}`,
  tenantSearchByUid: 'v1/tenants/search/by-uid',
  tenantAddExistingUser: (agencyId: number | string, buildingId: number | string) =>
    `v1/tenants/${agencyId}/${buildingId}/add-existing-user`,
  tenantProceedUnaccepted: (agencyId: number | string, buildingId: number | string, tenantId: number | string) =>
    `v1/tenants/${agencyId}/${buildingId}/${tenantId}/proceed-unaccepted`,
  tenancyAccept: (tenantId: number | string) => `v1/tenants/my/${tenantId}/accept`,
  tenancyDecline: (tenantId: number | string) => `v1/tenants/my/${tenantId}/decline`,

  // Renter-profile sharing consent. One grant covers the profile and the
  // documents behind it; one revocation closes both. The /my routes are
  // owner-only by construction — no permission an administrator can hold
  // reaches them.
  profileGrantsMine: 'v1/profile-grants/my',
  profileGrantApprove: (grantId: number | string) => `v1/profile-grants/my/${grantId}/approve`,
  profileGrantDecline: (grantId: number | string) => `v1/profile-grants/my/${grantId}/decline`,
  profileGrantRevoke: (grantId: number | string) => `v1/profile-grants/my/${grantId}/revoke`,
  profileGrantShareCodes: 'v1/profile-grants/my/share-codes',
  profileGrantRequests: (agencyId: number | string) => `v1/profile-grants/${agencyId}/requests`,
  profileGrantRedeem: (agencyId: number | string) => `v1/profile-grants/${agencyId}/share-codes/redeem`,
  profileGrantsByAgency: (agencyId: number | string) => `v1/profile-grants/${agencyId}`,

  // Re-opening a sealed verification snapshot.
  snapshotAccessGrants: (snapshotId: number | string) => `v1/snapshot-access/${snapshotId}/grants`,
  snapshotAccessRevoke: (grantId: number | string) => `v1/snapshot-access/grants/${grantId}/revoke`,
  tenantDocuments: 'v1/tenant-documents',
  tenantDocumentLandlordUpload: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/tenant-documents/${agencyId}/${buildingId}/${tenantId}/landlord-upload`,
  tenantDocumentById: (id: number | string) => `v1/tenant-documents/${id}`,
  tenantDocumentVersions: (id: number | string) => `v1/tenant-documents/${id}/versions`,
  tenantDocumentsMine: 'v1/tenant-documents/my-documents',
  tenantDocumentsByTenant: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/tenant-documents/tenant/${agencyId}/${buildingId}/${tenantId}`,
  tenantDocumentCurrentByType: (agencyId: number | string, buildingId: number | string, tenantId: number | string, documentType: string) => `v1/tenant-documents/tenant/${agencyId}/${buildingId}/${tenantId}/type/${documentType}/current`,
  statsPlatformOverview: 'v1/stats/platform/overview',
  statsPlatformTrends: 'v1/stats/platform/trends',
  statsAgencyOverview: (agencyId: number | string) => `v1/stats/agencies/${agencyId}/overview`,
  statsAgencyRent: (agencyId: number | string) => `v1/stats/agencies/${agencyId}/rent`,
  statsAgencyTrends: (agencyId: number | string) => `v1/stats/agencies/${agencyId}/trends`,
  statsAgencyOccupancyMovement: (agencyId: number | string) => `v1/stats/agencies/${agencyId}/occupancy-movement`,
  statsAgencyBuildings: (agencyId: number | string) => `v1/stats/agencies/${agencyId}/buildings`,
  statsPlatformOperations: 'v1/stats/platform/operations',
  statsPlatformOnboarding: 'v1/stats/platform/onboarding-funnel',
  statsPlatformGeo: 'v1/stats/platform/geo-coverage',
  authCachePermissions: 'v1/auth/cache/permissions',
  authCachePermissionsUser: (userId: number | string) => `v1/auth/cache/permissions/users/${userId}`,
  authCachePermissionsRole: (roleId: number | string) => `v1/auth/cache/permissions/roles/${roleId}`,
  authCachePermissionsAgency: (agencyId: number | string) => `v1/auth/cache/permissions/agencies/${agencyId}`,
  statsMyOverview: 'v1/stats/my/overview',
  statsMyRent: 'v1/stats/my/rent',
  statsMyOnboarding: 'v1/stats/my/onboarding',
  statsCaretakerOverview: 'v1/stats/caretaker/overview',
  statsCaretakerRentStatus: 'v1/stats/caretaker/rent-status',
  statsCaretakerMovementSchedule: 'v1/stats/caretaker/movement-schedule',
  statsCaretakerBuilding: (agencyId: number | string, buildingId: number | string) => `v1/stats/caretaker/buildings/${agencyId}/${buildingId}`,
  statsEcomSales: 'v1/stats/ecom/sales',
  statsEcomFulfilment: 'v1/stats/ecom/fulfilment',
  statsEcomCatalog: 'v1/stats/ecom/catalog',
  statsEcomCustomers: 'v1/stats/ecom/customers',
  statsEcomVouchers: 'v1/stats/ecom/vouchers',
  statsEcomOverview: 'v1/stats/ecom/overview',
  statsEcomTrends: 'v1/stats/ecom/trends',
  contractVariables: 'v1/contract-templates/variables',
  contractMaster: 'v1/contract-templates/master',
  contractAgency: (agencyId: number | string) => `v1/contract-templates/${agencyId}`,
  contractBuilding: (agencyId: number | string, buildingId: number | string) => `v1/contract-templates/${agencyId}/buildings/${buildingId}`,
  contractRoom: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/contract-templates/${agencyId}/buildings/${buildingId}/rooms/${roomId}`,
  contractCascadePreview: (agencyId: number | string) => `v1/contract-templates/${agencyId}/cascade-preview`,
  contractCascade: (agencyId: number | string) => `v1/contract-templates/${agencyId}/cascade`,
  contractPreview: (agencyId: number | string) => `v1/contract-templates/${agencyId}/preview`,
  contractValidate: (agencyId: number | string) => `v1/contract-templates/${agencyId}/validate`,
  contractReadiness: (agencyId: number | string) => `v1/contract-templates/${agencyId}/readiness`,
  leaseDocumentPdf: (agencyId: number | string, buildingId: number | string, leaseId: number | string) => `v1/lease-agreements/${agencyId}/${buildingId}/${leaseId}/document.pdf`,
  myLeaseDocumentPdf: (leaseId: number | string) => `v1/lease-agreements/${leaseId}/document.pdf`,
  leaseAgreements: 'v1/lease-agreements',
  leaseAgreementById: (id: number | string) => `v1/lease-agreements/${id}`,
  leaseGenerate: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/lease-agreements/${agencyId}/${buildingId}/${tenantId}/generate`,
  leaseVerifyAndGenerate: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/lease-agreements/${agencyId}/${buildingId}/${tenantId}/verify-and-generate`,
  leaseActivate: (agencyId: number | string, buildingId: number | string, leaseId: number | string) => `v1/lease-agreements/${agencyId}/${buildingId}/${leaseId}/activate`,
  leaseTenantSign: (leaseId: number | string) => `v1/lease-agreements/${leaseId}/tenant-sign`,
  leaseRefreshContract: (leaseId: number | string) => `v1/lease-agreements/${leaseId}/refresh-contract`,
  leaseTenantDecline: (leaseId: number | string) => `v1/lease-agreements/${leaseId}/tenant-decline`,
  leaseRenew: (id: number | string) => `v1/lease-agreements/${id}/renew`,
  leasesByTenant: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/lease-agreements/tenant/${agencyId}/${buildingId}/${tenantId}`,
  leasesByRoom: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/lease-agreements/room/${agencyId}/${buildingId}/${roomId}`,
  leasesByBuilding: (agencyId: number | string, buildingId: number | string) => `v1/lease-agreements/building/${agencyId}/${buildingId}`,
  leasesMine: 'v1/lease-agreements/my-leases',
  leaseAmendments: 'v1/lease-amendments',
  leaseAmendmentById: (id: number | string) => `v1/lease-amendments/${id}`,
  leaseAmendmentsByLease: (leaseAgreementId: number | string) => `v1/lease-amendments/lease-agreement/${leaseAgreementId}`,
  leaseAmendmentsByTenant: (tenantId: number | string) => `v1/lease-amendments/tenant/${tenantId}`,
  leaseAmendmentSubmit: (id: number | string) => `v1/lease-amendments/${id}/submit`,
  leaseAmendmentWithdraw: (id: number | string) => `v1/lease-amendments/${id}/withdraw`,
  leaseAmendmentAccept: (id: number | string) => `v1/lease-amendments/${id}/accept`,
  leaseAmendmentReject: (id: number | string) => `v1/lease-amendments/${id}/reject`,
  leaseAmendmentActivate: (id: number | string) => `v1/lease-amendments/${id}/activate`,
  leaseAmendmentsByStatus: (status: string) => `v1/lease-amendments/status/${status}`,
  roomApplications: 'v1/room-applications',
  roomApplicationById: (id: number | string) => `v1/room-applications/${id}`,
  roomApplicationsMine: 'v1/room-applications/my-applications',
  roomApplicationWithdraw: (id: number | string) => `v1/room-applications/${id}/withdraw`,
  roomApplicationDecision: (agencyId: number | string, buildingId: number | string, applicationId: number | string) => `v1/room-applications/${agencyId}/${buildingId}/${applicationId}/decision`,
  roomApplicationsByBuilding: (agencyId: number | string, buildingId: number | string) => `v1/room-applications/${agencyId}/${buildingId}`,
  roomApplicationsByRoom: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/room-applications/${agencyId}/${buildingId}/room/${roomId}`,
  tenantMessages: 'v1/tenant-messages',
  tenantMessageById: (id: number | string) => `v1/tenant-messages/${id}`,
  tenantMessageStatus: (id: number | string) => `v1/tenant-messages/${id}/status`,
  tenantMessagesByTenant: (tenantId: number | string) => `v1/tenant-messages/tenant/${tenantId}`,
  tenantMessagesMine: 'v1/tenant-messages/my-messages',
  tenantMessagesByBuilding: (buildingId: number | string) => `v1/tenant-messages/building/${buildingId}`,
  tenantMessagesByStatus: (status: string) => `v1/tenant-messages/status/${status}`,
  tenantMessagesByType: (type: string) => `v1/tenant-messages/type/${type}`,
  tenantMessageNewCount: (tenantId: number | string) => `v1/tenant-messages/tenant/${tenantId}/new/count`,
  tenantMessageUnresolvedCount: 'v1/tenant-messages/unresolved/count',
  verificationSnapshots: 'v1/verification-snapshots',
  verificationSnapshotVerify: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/verification-snapshots/verify/${agencyId}/${buildingId}/${tenantId}`,
  verificationSnapshotById: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) => `v1/verification-snapshots/${agencyId}/${buildingId}/${tenantId}/${id}`,
  verificationSnapshotsByTenant: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/verification-snapshots/tenant/${agencyId}/${buildingId}/${tenantId}`,
  verificationSnapshotCurrentForTenant: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/verification-snapshots/tenant/${agencyId}/${buildingId}/${tenantId}/current`,
  verificationSnapshotRevise: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `v1/verification-snapshots/revise/${agencyId}/${buildingId}/${tenantId}`,
  verificationSnapshotsByType: (snapshotType: string) => `v1/verification-snapshots/type/${snapshotType}`,
  verificationSnapshotsCurrent: 'v1/verification-snapshots/current',
  verificationSnapshotIpfsCid: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) => `v1/verification-snapshots/${agencyId}/${buildingId}/${tenantId}/${id}/ipfs-cid`,
  verificationSnapshotMarkNotCurrent: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) => `v1/verification-snapshots/${agencyId}/${buildingId}/${tenantId}/${id}/mark-not-current`,
  verificationSnapshotVerifyIntegrity: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) => `v1/verification-snapshots/${agencyId}/${buildingId}/${tenantId}/${id}/verify-integrity`,
  rentPayments: 'v1/rent-payments',
  rentPaymentsMine: 'v1/rent-payments/user/me',
  rentPaymentsByUser: (userId: number | string) => `v1/rent-payments/user/${userId}`,
  rentPaymentsByBuilding: (agencyId: number | string, buildingId: number | string) => `v1/rent-payments/${agencyId}/${buildingId}`,
  rentPaymentById: (agencyId: number | string, buildingId: number | string, id: number | string) => `v1/rent-payments/${agencyId}/${buildingId}/${id}`,
  rentPaymentTransactions: (agencyId: number | string, buildingId: number | string, id: number | string) => `v1/rent-payments/${agencyId}/${buildingId}/${id}/transactions`,
  rentPaymentPreview: (agencyId: number | string, buildingId: number | string) => `v1/rent-payments/${agencyId}/${buildingId}/preview`,
  rentPaymentOverdue: (agencyId: number | string, buildingId: number | string) => `v1/rent-payments/${agencyId}/${buildingId}/overdue`,
  rentPaymentSummary: (agencyId: number | string, buildingId: number | string) => `v1/rent-payments/${agencyId}/${buildingId}/summary`,
  rentArrearsStatus: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/month/${month}/status`,
  rentArrearsGenerate: (agencyId: number | string, buildingId: number | string) => `v1/rent-arrears/${agencyId}/${buildingId}/generate`,
  rentArrearsConfirm: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/month/${month}/confirm`,
  rentArrearsPendingTasks: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/month/${month}/pending-tasks`,
  rentArrearsForTenant: (agencyId: number | string, buildingId: number | string, tenantId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/${tenantId}/month/${month}`,
  rentArrearsRooms: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/rooms/month/${month}`,
  rentArrearsTenants: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/tenants/month/${month}`,
  rentArrearsReport: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-arrears/${agencyId}/${buildingId}/report/month/${month}`,
  myArrearsCurrent: 'v1/my-arrears/current',
  myArrearsForMonth: (month: string) => `v1/my-arrears/month/${month}`,
  rentAdjustmentOneOff: (agencyId: number | string, buildingId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/one-off`,
  rentAdjustmentWaive: (agencyId: number | string, buildingId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/waive`,
  rentAdjustmentAdjust: (agencyId: number | string, buildingId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/adjust`,
  rentAdjustmentBulkCharge: (agencyId: number | string, buildingId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/bulk-charge`,
  rentAdjustmentBulkWaive: (agencyId: number | string, buildingId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/bulk-waive`,
  rentAdjustmentChargeHistory: (agencyId: number | string, buildingId: number | string, chargeId: number | string) => `v1/rent-adjustments/${agencyId}/${buildingId}/charge/${chargeId}/history`,
  rentAdjustmentMonthHistory: (agencyId: number | string, buildingId: number | string, month: string) => `v1/rent-adjustments/${agencyId}/${buildingId}/month/${month}/history`,
  rentChargeTemplates: (agencyId: number | string, buildingId: number | string) => `v1/rent-utilities-charge-templates/${agencyId}/${buildingId}`,
  rentChargeTemplatesByRoom: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `v1/rent-utilities-charge-templates/${agencyId}/${buildingId}/room/${roomId}`,
  rentChargeTemplateById: (agencyId: number | string, buildingId: number | string, templateId: number | string) => `v1/rent-utilities-charge-templates/${agencyId}/${buildingId}/${templateId}`,
  rentMeterReading: (agencyId: number | string, buildingId: number | string, chargeId: number | string) => `v1/utility-charges/${agencyId}/${buildingId}/charge/${chargeId}/reading`,
  rentReadingsApplyUniform: (agencyId: number | string, buildingId: number | string, month: string) => `v1/utility-charges/${agencyId}/${buildingId}/month/${month}/readings/apply-uniform`,
  rentReadingsApplyUniformSubset: (agencyId: number | string, buildingId: number | string, month: string) => `v1/utility-charges/${agencyId}/${buildingId}/month/${month}/readings/apply-uniform-subset`,
  rentBulkReadings: (agencyId: number | string, buildingId: number | string) => `v1/utility-charges/${agencyId}/${buildingId}/bulk-readings`,
  chatMyConversations: 'v1/chat/conversations/my',
  chatStartConversation: 'v1/chat/conversations/start',
  chatMessages: (conversationId: number | string) => `v1/chat/conversations/${conversationId}/messages`,
  chatOpenConversations: 'v1/chat/conversations/open',
  chatClaimedConversations: 'v1/chat/conversations/claimed',
  chatClaim: (conversationId: number | string) => `v1/chat/conversations/${conversationId}/claim`,
  chatUnclaim: (conversationId: number | string) => `v1/chat/conversations/${conversationId}/unclaim`,
  chatClose: (conversationId: number | string) => `v1/chat/conversations/${conversationId}/close`,
  notifications: 'v1/notifications',
  notificationsUnread: 'v1/notifications/unread',
  notificationsStarred: 'v1/notifications/starred',
  notificationsUnreadCount: 'v1/notifications/unread-count',
  notificationRead: (id: number | string) => `v1/notifications/${id}/read`,
  notificationsReadAll: 'v1/notifications/read-all',
  notificationStar: (id: number | string) => `v1/notifications/${id}/star`,
  notificationTokens: 'v1/notifications/tokens',
  notificationTokenByValue: (token: string) => `v1/notifications/tokens/${encodeURIComponent(token)}`,
  notificationAdminMedia: 'v1/notifications/admin/media',
  notificationAdminSend: 'v1/notifications/admin/send',
  appCheck: 'v1/app/check',
  appNoticeAcknowledge: (noticeId: number | string) => `v1/app/notices/${noticeId}/acknowledge`,
  appAdminNotices: 'v1/app/admin/notices',
  appAdminNoticeById: (id: number | string) => `v1/app/admin/notices/${id}`,
  appAdminNoticeToggle: (id: number | string) => `v1/app/admin/notices/${id}/toggle`,
  appAdminVersionConfigs: 'v1/app/admin/version-config',
  appAdminVersionConfigByPlatform: (platform: string) => `v1/app/admin/version-config/${platform}`,
  logoutAllDevices: 'v1/auth/logout-all-devices',
  adminForceLogout: (userId: number | string) => `v1/auth/admin/force-logout/${userId}`,
  roles: 'v1/roles',
  roleById: (id: number | string) => `v1/roles/${id}`,
  roleTogglePermission: 'v1/roles/permissions/toggle',
  agencyRoles: 'v1/roles/agency-roles',
  userRoles: (userId: number | string) => `v1/roles/users/${userId}/roles`,
  permissions: 'v1/permissions',
  permissionById: (id: number | string) => `v1/permissions/${id}`,
  geoRegions: 'v1/geo/regions',
  geoRegionById: (id: string) => `v1/geo/regions/${id}`,
  geoRegionRoots: 'v1/geo/regions/roots',
  geoRegionLookup: 'v1/geo/regions/lookup',
  geoRegionContainsPoint: 'v1/geo/regions/contains-point',
  geoLandmarks: 'v1/geo/landmarks',
  geoLandmarkById: (id: string) => `v1/geo/landmarks/${id}`,
  geoLandmarksNearby: 'v1/geo/landmarks/nearby',
} as const;
