export const RoutePaths = {
  splash: '/',
  login: '/login',
  signup: '/signup',
  phoneLogin: '/phone-login',
  verifyPhone: '/signup/verify-phone',
  setPassword: '/password-set',
  forgotPassword: '/forgot-password',
  resetPassword: '/password-reset',
  changePassword: '/change-password',
  home: '/home',
  users: '/users',
  userCreate: '/users/new',
  userDetail: (id: number | string) => `/users/${id}`,
  userEdit: (id: number | string) => `/users/${id}/edit`,
  userProfile: '/profile',
  adminUsers: '/admin/users',
  ecommerce: '/ecommerce',
  ecomProducts: '/ecommerce/products',
  ecomProductDetail: (id: number | string) => `/ecommerce/products/${id}`,
  ecomOrders: '/ecommerce/orders',
  ecomOrderDetail: (id: number | string) => `/ecommerce/orders/${id}`,
  ecomCategories: '/ecommerce/categories',
  ecomCategoryDetail: (id: number | string) => `/ecommerce/categories/${id}`,
  ecomStores: '/ecommerce/stores',
  ecomStoreCreate: '/ecommerce/stores/new',
  ecomStoreDetail: (id: number | string) => `/ecommerce/stores/${id}`,
  ecomStoreEdit: (id: number | string) => `/ecommerce/stores/${id}/edit`,
  addresses: '/addresses',
  addressRecords: '/addresses/records',
  addressCreate: '/addresses/records/new',
  addressDetail: (id: number | string) => `/addresses/records/${id}`,
  addressEdit: (id: number | string) => `/addresses/records/${id}/edit`,
  ecomCustomers: '/ecommerce/customers'
} as const;
