export const RoutePaths = {
  splash: '/',
  login: '/login',
  signup: '/signup',
  phoneLogin: '/phone-login',
  verifyPhone: '/signup/verify-phone',
  setPassword: '/password-set',
  forgotPassword: '/forgot-password',
  resetPassword: '/password-reset',
  changePassword: '/change-password',
  home: '/home',
  caretakerBuilding: (agencyId: number | string, buildingId: number | string) =>
    `/home/buildings/${agencyId}/${buildingId}`,
  users: '/admin/users',
  userCreate: '/admin/users/new',
  userDetail: (id: number | string) => `/admin/users/${id}`,
  userEdit: (id: number | string) => `/admin/users/${id}/edit`,
  userProfile: '/me',
  adminUsers: '/admin/users',
  ecommerce: '/admin/ecommerce',
  ecomProducts: '/admin/ecommerce/products',
  ecomProductDetail: (id: number | string) => `/admin/ecommerce/products/${id}`,
  ecomOrders: '/admin/ecommerce/orders',
  ecomOrderDetail: (id: number | string) => `/admin/ecommerce/orders/${id}`,
  ecomCategories: '/admin/ecommerce/categories',
  ecomCategoryDetail: (id: number | string) => `/admin/ecommerce/categories/${id}`,
  ecomStores: '/admin/ecommerce/stores',
  ecomStoreCreate: '/admin/ecommerce/stores/new',
  ecomStoreDetail: (id: number | string) => `/admin/ecommerce/stores/${id}`,
  ecomStoreEdit: (id: number | string) => `/admin/ecommerce/stores/${id}/edit`,
  addresses: '/admin/addresses',
  addressRecords: '/admin/addresses/records',
  addressCreate: '/admin/addresses/records/new',
  addressDetail: (id: number | string) => `/admin/addresses/records/${id}`,
  addressEdit: (id: number | string) => `/admin/addresses/records/${id}/edit`,
  ecomCustomers: '/admin/ecommerce/customers',
  roles: '/admin/access-control/roles',
  roleCreate: '/admin/access-control/roles/new',
  roleDetail: (id: number | string) => `/admin/access-control/roles/${id}`,
  roleEdit: (id: number | string) => `/admin/access-control/roles/${id}/edit`,
  permissions: '/admin/access-control/permissions',
  geoRegions: '/admin/geo/regions',
  geoRegionCreate: '/admin/geo/regions/new',
  geoRegionDetail: (id: string) => `/admin/geo/regions/${id}`,
  geoRegionEdit: (id: string) => `/admin/geo/regions/${id}/edit`,
  geoLandmarks: '/admin/geo/landmarks',
  geoLandmarkCreate: '/admin/geo/landmarks/new',
  geoLandmarkDetail: (id: string) => `/admin/geo/landmarks/${id}`,
  geoLandmarkEdit: (id: string) => `/admin/geo/landmarks/${id}/edit`,
  ecomProductCreate: '/admin/ecommerce/products/new',
  ecomProductEdit: (id: number | string) => `/admin/ecommerce/products/${id}/edit`,
  ecomProductMedia: (id: number | string) => `/admin/ecommerce/products/${id}/media`,
  ecomProductDiscounts: (id: number | string) => `/admin/ecommerce/products/${id}/discounts`,
  ecomCategoryCreate: '/admin/ecommerce/categories/new',
  ecomCategoryEdit: (id: number | string) => `/admin/ecommerce/categories/${id}/edit`,
  ecomTags: '/admin/ecommerce/tags',
  ecomTagCreate: '/admin/ecommerce/tags/new',
  ecomTagDetail: (id: number | string) => `/admin/ecommerce/tags/${id}`,
  customerGroups: '/admin/ecommerce/customer-groups',
  customerGroupCreate: '/admin/ecommerce/customer-groups/new',
  customerGroupDetail: (id: number | string) => `/admin/ecommerce/customer-groups/${id}`,
  customerGroupEdit: (id: number | string) => `/admin/ecommerce/customer-groups/${id}/edit`,
  vouchers: '/admin/ecommerce/vouchers',
  voucherCreate: '/admin/ecommerce/vouchers/new',
  voucherDetail: (id: number | string) => `/admin/ecommerce/vouchers/${id}`,
  voucherEdit: (id: number | string) => `/admin/ecommerce/vouchers/${id}/edit`,
  payments: '/admin/ecommerce/payments',
  paymentDetail: (id: number | string) => `/admin/ecommerce/payments/${id}`,
  partialPaymentPolicies: '/admin/ecommerce/partial-payment-policies',
  partialPaymentPolicyCreate: '/admin/ecommerce/partial-payment-policies/new',
  partialPaymentPolicyEdit: (id: number | string) => `/admin/ecommerce/partial-payment-policies/${id}/edit`,
  deliveryAddresses: '/me/delivery-addresses',
  deliveryAddressCreate: '/me/delivery-addresses/new',
  deliveryAddressDetail: (id: number | string) => `/me/delivery-addresses/${id}`,
  deliveryAddressEdit: (id: number | string) => `/me/delivery-addresses/${id}/edit`,
  agencies: '/admin/housing/agencies',
  agencyCreate: '/admin/housing/agencies/new',
  agencyDetail: (id: number | string) => `/admin/housing/agencies/${id}`,
  agencyEdit: (id: number | string) => `/admin/housing/agencies/${id}/edit`,
  myAgencies: '/admin/housing/my-agencies',
  buildings: '/admin/housing/buildings',
  buildingCreate: '/admin/housing/buildings/new',
  buildingDetail: (agencyId: number | string, buildingId: number | string) => `/admin/housing/buildings/${agencyId}/${buildingId}`,
  buildingEdit: (agencyId: number | string, buildingId: number | string) => `/admin/housing/buildings/${agencyId}/${buildingId}/edit`,
  roomDetail: (agencyId: number | string, buildingId: number | string, roomId: number | string) => `/admin/housing/buildings/${agencyId}/${buildingId}/rooms/${roomId}`,
  availableRooms: '/rooms',
  tenants: '/admin/tenants',
  tenantCreate: '/admin/tenants/new',
  tenantAddExisting: '/admin/tenants/add-existing',
  tenantDetail: (agencyId: number | string, buildingId: number | string, tenantId: number | string) => `/admin/tenants/${agencyId}/${buildingId}/${tenantId}`,
  tenantProfile: '/me/tenancy',
  myProfileSharing: '/me/profile-sharing',
  renterProfile: '/me/tenancy',
  renterProfileEdit: '/me/renter-profile',
  leases: '/admin/tenants/leases',
  leaseDetail: (id: number | string) => `/admin/tenants/leases/${id}`,
  myLeases: '/me/leases',
  amendments: '/admin/tenants/amendments',
  amendmentDetail: (id: number | string) => `/admin/tenants/amendments/${id}`,
  roomApplications: '/admin/tenants/applications',
  roomApplicationDetail: (id: number | string) => `/admin/tenants/applications/${id}`,
  myRoomApplications: '/me/applications',
  agencyProfileSharing: '/admin/tenants/profile-sharing',
  /** Reached through the tenant it belongs to — there is no agency-wide document list. */
  tenantDocumentDetail: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) =>
    `/admin/tenants/${agencyId}/${buildingId}/${tenantId}/documents/${id}`,
  myTenantDocuments: '/me/documents',
  tenantMessages: '/admin/tenants/messages',
  tenantMessageDetail: (id: number | string) => `/admin/tenants/messages/${id}`,
  myTenantMessages: '/me/messages',
  verificationSnapshotDetail: (agencyId: number | string, buildingId: number | string, tenantId: number | string, id: number | string) => `/admin/tenants/verification-snapshots/${agencyId}/${buildingId}/${tenantId}/${id}`,
  rentPayments: '/admin/rent/payments',
  rentPaymentCreate: '/admin/rent/payments/new',
  rentPaymentDetail: (agencyId: number | string, buildingId: number | string, id: number | string) => `/admin/rent/payments/${agencyId}/${buildingId}/${id}`,
  rentPortfolioOverdue: '/admin/rent/portfolio-overdue',
  myRentPayments: '/me/rent-payments',
  rentArrears: '/admin/rent/arrears',
  rentDeposits: '/admin/rent/deposits',
  myArrears: '/me/arrears',
  rentAdjustments: '/admin/rent/adjustments',
  rentChargeTemplates: '/admin/rent/charge-templates',
  rentMeterReadings: '/admin/rent/meter-readings',
  chat: '/chat',
  chatConversation: (id: number | string) => `/chat/${id}`,
  notifications: '/notifications',
  notificationsAdmin: '/admin/notifications/broadcast',
  notificationChannels: '/admin/notifications/channels',
  notificationPreferences: '/me/notification-preferences',
  appNotices: '/admin/app-management/notices',
  appNoticeCreate: '/admin/app-management/notices/new',
  appNoticeEdit: (id: number | string) => `/admin/app-management/notices/${id}/edit`,
  appVersionConfig: '/admin/app-management/version-config',
  settings: '/admin/settings',
  cacheManager: '/admin/settings/cache',
  contractMasterTemplate: '/admin/contracts/master',
  agencyContractTemplate: (agencyId: number | string) => `/admin/contracts/agencies/${agencyId}`,
  buildingContractTemplate: (agencyId: number | string, buildingId: number | string) =>
    `/admin/contracts/agencies/${agencyId}/buildings/${buildingId}`,
  roomContractTemplate: (agencyId: number | string, buildingId: number | string, roomId: number | string) =>
    `/admin/contracts/agencies/${agencyId}/buildings/${buildingId}/rooms/${roomId}`,
  shop: '/shop',
  shopProduct: (id: number | string) => `/shop/products/${id}`,
  cart: '/shop/cart',
  checkout: '/shop/checkout',
  myOrders: '/shop/my-orders',
  myOrderDetail: (id: number | string) => `/shop/my-orders/${id}`,
  myVouchers: '/shop/my-vouchers',
  profileEdit: '/me/edit',
  myLeaseDetail: (id: number | string) => `/me/leases/${id}`,
  myTenantDocumentDetail: (id: number | string) => `/me/documents/${id}`,
  myTenantMessageDetail: (id: number | string) => `/me/messages/${id}`,
  myRoomApplicationDetail: (id: number | string) => `/me/applications/${id}`,
  myRentPaymentDetail: (agencyId: number | string, buildingId: number | string, id: number | string) =>
    `/me/rent-payments/${agencyId}/${buildingId}/${id}`
} as const;
